### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by couto** [madrobby/semicolon.js#3]
Tests are missing.
How can you ensure that it works?

**Comment by madrobby** [comment]
Obviously, the `;` makes the code stable, secure and reliable. D'oh.

**Comment by couto** [comment]
So you can assure me third-party code, that might pollut the enviroment, won't affect the `;` behaviour in any way possible? <img class="emoji" title=":trollface:" alt=":trollface:" src="https://a248.e.akamai.net/assets.github.com/images/icons/emoji/trollface.png?v5" height="20" width="20" align="absmiddle">

**Comment by madrobby** [comment]
If you like you can escalate the issue with our (paid) enterprise support team.
